
export const GET_COLORS = "GET_COLORS";
export const GET_COLORS_BY_QUERY = "GET_COLORS_BY_QUERY";
export const GET_COLOR_BY_ID = "GET_COLOR_BY_ID";
export const ADD_COLOR = "ADD_COLOR";
export const UPDATE_COLOR = "UPDATE_COLOR";
export const DELETE_COLOR = "DELETE_COLOR";
export const DELETE_COLORS_BY_RANGE = "DELETE_COLORS_BY_RANGE";
export const SELECTED_COLOR_NULL = "SELECTED_COLOR_NULL";

export const OPEN_COLOR_SIDEBAR = "OPEN_COLOR_SIDEBAR";
export const DROP_DOWN_COLORS = "DROP_DOWN_COLORS";
