
export const GET_STATUSES = "GET_STATUSES";
export const GET_STATUSES_BY_QUERY = "GET_STATUSES_BY_QUERY";
export const GET_STATUS_BY_ID = "GET_STATUS_BY_ID";
export const ADD_STATUS = "ADD_STATUS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const DELETE_STATUS = "DELETE_STATUS";
export const DELETE_STATUSES_BY_RANGE = "DELETE_STATUSES_BY_RANGE";
export const SELECTED_STATUS_NULL = "SELECTED_STATUS_NULL";
export const GET_STATUS_TYPES = "GET_STATUS_TYPES";


export const OPEN_STATUS_SIDEBAR = "OPEN_STATUS_SIDEBAR";
export const DROP_DOWN_STATUSES = "DROP_DOWN_STATUSES";
