
export const GET_SINGLE_STYLES = "GET_SINGLE_STYLES";
export const GET_SINGLE_STYLES_BY_QUERY = "GET_SINGLE_STYLES_BY_QUERY";
export const GET_SINGLE_STYLE_BY_ID = "GET_SINGLE_STYLES_BY_ID";
export const ADD_SINGLE_STYLE = "ADD_SINGLE_STYLE";
export const UPDATE_SINGLE_STYLE = "UPDATE_SINGLE_STYLE";
export const DELETE_SINGLE_STYLE = "DELETE_SINGLE_STYLE";
export const DELETE_SINGLE_STYLES_BY_RANGE = "DELETE_SINGLE_STYLES_BY_RANGE";
export const SELECTED_SINGLE_STYLE_NULL = "SELECTED_SINGLE_STYLE_NULL";


export const OPEN_SINGLE_STYLE_SIDEBER = "OPEN_SINGLE_STYLE_SIDEBER";
export const OPEN_SINGLE_STYLE_FORM = "OPEN_SINGLE_STYLE_FORM";

export const DROP_DOWN_SINGLE_STYLES = 'DROP_DOWN_SINGLE_STYLES';

export const UPLOAD_SINGLE_STYLE_IMAGE = 'UPLOAD_SINGLE_STYLE_IMAGE';
export const GET_SINGLE_STYLE_UPLOAD_IMAGE = 'GET_SINGLE_STYLE_UPLOAD_IMAGE';
export const IS_FILE_UPLOADED_COMPLETE = 'IS_FILE_UPLOADED_COMPLETE';