
export const GET_SIZE_GROUPS = "GET_SIZE_GROUPS";
export const GET_SIZE_GROUPS_BY_QUERY = "GET_SIZE_GROUPS_BY_QUERY";
export const GET_SIZE_GROUP_BY_ID = "GET_SIZE_GROUP_BY_ID";
export const ADD_SIZE_GROUP = "ADD_SIZE_GROUP";
export const UPDATE_SIZE_GROUP = "UPDATE_SIZE_GROUP";
export const DELETE_SIZE_GROUP = "DELETE_SIZE_GROUP";
export const DELETE_SIZE_GROUP_BY_RANGE = "DELETE_SIZE_GROUP_BY_RANGE";
export const SELECTED_SIZE_GROUP_NULL = "SELECTED_SIZE_GROUP_NULL";

export const OPEN_SIZE_GROUP_SIDEBAR = "OPEN_SIZE_GROUP_SIDEBAR";
export const DROP_DOWN_SIZE_GROUPS = "DROP_DOWN_SIZE_GROUPS";
