
export const GET_PRE_COSTINGS = "GET_PRE_COSTINGS";
export const GET_PRE_COSTINGS_BY_QUERY = "GET_PRE_COSTINGS_BY_QUERY";
export const GET_PRE_COSTING_BY_ID = "GET_PRE_COSTINGS_BY_ID";
export const ADD_PRE_COSTING = "ADD_PRE_COSTING";
export const UPDATE_PRE_COSTING = "UPDATE_PRE_COSTING";
export const DELETE_PRE_COSTING = "DELETE_PRE_COSTING";
export const DELETE_PRE_COSTINGS_BY_RANGE = "DELETE_PRE_COSTINGS_BY_RANGE";

export const SELECTED_PRE_COSTING_NULL = "SELECTED_PRE_COSTING_NULL";
export const DROP_DOWN_PRE_COSTINGS = 'DROP_DOWN_PRE_COSTINGS';