
export const GET_SET_STYLES = "GET_SET_STYLES";
export const GET_SET_STYLES_BY_QUERY = "GET_SET_STYLES_BY_QUERY";
export const GET_SET_STYLE_BY_ID = "GET_SET_STYLES_BY_ID";
export const ADD_SET_STYLE = "ADD_SINGLE_SET";
export const UPDATE_SET_STYLE = "UPDATE_SET_STYLE";
export const DELETE_SET_STYLE = "DELETE_SET_STYLE";
export const DELETE_SET_STYLES_BY_RANGE = "DELETE_SET_STYLES_BY_RANGE";
export const SELECTED_SET_STYLE_NULL = "SELECTED_SET_STYLE_NULL";


export const OPEN_SET_STYLE_SIDEBER = "OPEN_SET_STYLE_SIDEBER";
export const OPEN_SET_STYLE_FORM = "OPEN_SET_STYLE_FORM";

export const DROP_DOWN_SET_STYLES = 'DROP_DOWN_SET_STYLES';