
export const GET_SEASONS = "GET_SEASONS";
export const GET_SEASONS_BY_QUERY = "GET_SEASONS_BY_QUERY";
export const GET_SEASON_BY_ID = "GET_SEASON_BY_ID";
export const ADD_SEASON = "ADD_SEASON";
export const UPDATE_SEASON = "UPDATE_SEASON";
export const DELETE_SEASON = "DELETE_SEASON";
export const DELETE_SEASONS_BY_RANGE = "DELETE_SEASONS_BY_RANGE";
export const SELECTED_SEASON_NULL = "SELECTED_SEASON_NULL";

export const OPEN_SEASON_SIDEBAR = "OPEN_SEASON_SIDEBAR";
export const DROP_DOWN_SEASONS = "DROP_DOWN_SEASONS";
