
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_DEPARTMENTS_BY_QUERY = "GET_DEPARTMENTS_BY_QUERY";
export const GET_DEPARTMENT_BY_ID = "GET_DEPARTMENTS_BY_ID";
export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
export const DELETE_DEPARTMENTS_BY_RANGE = "DELETE_DEPARTMENTS_BY_RANGE";
export const SELECTED_DEPARTMENT_NULL = "SELECTED_DEPARTMENT_NULL";

export const OPEN_DEPARTMENT_SIDEBAR = "OPEN_DEPARTMENT_SIDEBAR";
export const DROP_DOWN_DEPARTMENTS = "DROP_DOWN_DEPARTMENTS";
