
export const GET_BUYERS = "GET_BUYERS";
export const GET_BUYERS_BY_QUERY = "GET_BUYERS_BY_QUERY";
export const GET_BUYER_BY_ID = "GET_BUYERS_BY_ID";
export const ADD_BUYER = "ADD_BUYER";
export const UPDATE_BUYER = "UPDATE_BUYER";
export const DELETE_BUYER = "DELETE_BUYER";
export const DELETE_BUYERS_BY_RANGE = "DELETE_BUYERS_BY_RANGE";
export const SELECTED_BUYER_NULL = "SELECTED_BUYER_NULL";

export const OPEN_BUYER_SIDEBER = "OPEN_BUYER_SIDEBER";
export const DROP_DOWN_BUYERS = "DROP_DOWN_BUYERS";
export const IS_ASSIGN_AGENT = "IS_ASSIGN_AGENT";
export const IS_ASSIGN_PRODUCT_DEVELOPER = "IS_ASSIGN_PRODUCT_DEVELOPER";
