
export const GET_PURCHASE_ORDERS = "GET_PURCHASE_ORDERS";
export const GET_PURCHASE_ORDERS_BY_QUERY = "GET_PURCHASE_ORDERS_BY_QUERY";
export const GET_PURCHASE_ORDER_BY_ID = "GET_PURCHASE_ORDERS_BY_ID";
export const ADD_PURCHASE_ORDER = "ADD_PURCHASE_ORDER";
export const UPDATE_PURCHASE_ORDER = "UPDATE_PURCHASE_ORDER";
export const DELETE_PURCHASE_ORDER = "DELETE_PURCHASE_ORDER";
export const DELETE_PURCHASE_ORDERS_BY_RANGE = "DELETE_PURCHASE_ORDERS_BY_RANGE";
export const SELECTED_PURCHASE_ORDER_NULL = "SELECTED_PURCHASE_ORDER_NULL";


export const OPEN_PURCHASE_ORDER_SIDEBER = "OPEN_PURCHASE_ORDER_SIDEBER";
export const OPEN_PURCHASE_ORDER_FORM = "OPEN_PURCHASE_ORDER_FORM";
export const CONTROL_SET_PURCHASE_ORDER = "CONTROL_SET_PURCHASE_ORDER";
export const CONTROL_SINGLE_PURCHASE_ORDER = "CONTROL_SINGLE_PURCHASE_ORDER";
export const TOTAL_SELECTED_STYLES = "TOTAL_SELECTED_STYLES";

