
export const GET_BUYER_DEPARTMENTS = "GET_BUYER_DEPARTMENTS";
export const GET_BUYER_DEPARTMENTS_BY_QUERY = "GET_BUYER_DEPARTMENTS_BY_QUERY";
export const GET_BUYER_DEPARTMENT_BY_ID = "GET_BUYER_DEPARTMENT_BY_ID";
export const ADD_BUYER_DEPARTMENT = "ADD_BUYER_DEPARTMENT";
export const UPDATE_BUYER_DEPARTMENT = "UPDATE_BUYER_DEPARTMENT";
export const DELETE_BUYER_DEPARTMENT = "DELETE_BUYER_DEPARTMENT";
export const DELETE_BUYER_DEPARTMENTS_BY_RANGE = "DELETE_BUYER_DEPARTMENTS_BY_RANGE";
export const SELECTED_BUYER_DEPARTMENT_NULL = "SELECTED_BUYER_DEPARTMENT_NULL";

export const OPEN_BUYER_DEPARTMENT_SIDEBAR = "OPEN_BUYER_DEPARTMENT_SIDEBAR";
export const DROP_DOWN_BUYER_DEPARTMENTS = "DROP_DOWN_BUYER_DEPARTMENTS";
